apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitopsapp
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: gitopsapp
  template:
    metadata:
      labels:
        app: gitopsapp
    spec:
      containers:
        - image: fleatbnp/express-microservice:8a95b2c
          name: gitopsapp
          ports:
            - containerPort: 3000
